# Generated by Django 5.1 on 2024-08-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college_student',
            old_name='student_description',
            new_name='stu_description',
        ),
        migrations.RenameField(
            model_name='college_student',
            old_name='student_image',
            new_name='stu_image',
        ),
        migrations.RenameField(
            model_name='college_student',
            old_name='student_name',
            new_name='stu_name',
        ),
        migrations.RenameField(
            model_name='college_student',
            old_name='student_view_count',
            new_name='stu_view_count',
        ),
    ]
