# Generated by Django 5.1 on 2024-08-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_student_description_college_student_stu_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college_student',
            name='stu_image',
            field=models.ImageField(upload_to='student_img'),
        ),
    ]
